### ISSUE TITLE
DHARMa.helpers error message with Brms Ordinal Logit model  

### ISSUE THREAD

**Issue by GLad-Arioch** [Pakillo/DHARMa.helpers#1]
Hi Franscico,

Thank you for providing us with this helpful bridge between brms and dharma.

I applied 

 dh_check_brms(mymodel, integer = TRUE)

to a repeated measures 3 levels ordinal logit.

The following error message is issued:

Error in t.default(brms::posterior_epred(model, ndraws = nsamples, re.form = NA)) : 
  argument is not a matrix

What should I do?

Best regards,

Guillaume

**Comment by Pakillo** [comment]
Hi Guillaume,

I'm afraid that ordinal models are not supported (yet). I've added a note in the documentation to make that clear. I'm unclear how far DHARMa supports ordinal models too, hope this thread is useful to you: https://github.com/florianhartig/DHARMa/issues/174

Cheers

**Comment by StaffanBetner** [comment]
Sorry for posting in this closed issue, however, for ordinal models (in the simplest cases, where the effect doesn't vary due to level, the thresholds doesn't vary, etc.) we can replace posterior_epred with posterior_linpred, and get reasonable results.

**Comment by Pakillo** [comment]
Thanks @StaffanBetner ! That's helpful to know

Cheers
